### ISSUE TITLE
Loading fonts through SVG makes it slow

### ISSUE THREAD

**Issue by mnot** [bramp/js-sequence-diagrams#153]
Loading https://www.mnot.net/blog/2016/04/22/ideal-http with the default `hand` theme takes between 7-12 seconds on modern browsers / hardware. Changing to another font (e.g., `sans-serif`) reduces page load time to under a second.

**Comment by bramp** [comment]
Yes, I am aware and apologise that loading the hand drawn font is terribly slow.  This is a limitation in the Raphael.js library I use for generating the SVG. So that Raphael can maintain it's compatibility with VML (for IE), it includes the font as a vector within the SVG.

I'm currently working on 2.0 of js-sequence-diagrams[1] that moves to the snap.svg library. This drops the legacy VML support, and allows the SVG to be styled with CSS, and use standard fonts.

[1] https://github.com/bramp/js-sequence-diagrams/tree/svg

**Comment by mnot** [comment]
No worries, thanks!

**Comment by pkanthi** [comment]
Great. What would be the expected release timeline for js-sequence-diagrams 2.0?

**Comment by bramp** [comment]
ok js-sequence-diagram 2.0 is now out, and the font can be specified via normal CSS.
