### ISSUE TITLE
Double dot to mark actors as objects is not possible

### ISSUE THREAD

**Issue by Yserz** [bramp/js-sequence-diagrams#81]
As far as I tested it on the website for this project it's not possible to mark actors as objects with a double dot (:).

Example:
```
:Andrew->China: Says Hello
```

**Comment by bramp** [comment]
That is correct. An actor is defined as ```[^\->:\n,]+```, that is one or more characters except ```->:\n,```. I could try and get creative with parsing, so that : could be somewhere within the name except at the end, however it might just get tricky.

I understand how that would be inconvenient for object diagrams, but right now I don't have a good solution. I'm happy to consider alternatives, but will close this ticket until one is suggested.
